// Catálogo curado de herramientas IA mayo 2026.
// Solo herramientas verificadas y usables hoy.

export type HerramientaCategory =
  | "chatbot"
  | "imagen"
  | "video"
  | "audio"
  | "investigacion"
  | "trabajo"
  | "developer"
  | "agente"
  | "local";

export type HerramientaPrice = "gratis" | "freemium" | "pago" | "api";

export type Herramienta = {
  id: string;
  name: string;
  by: string;
  category: HerramientaCategory;
  price: HerramientaPrice;
  url: string;
  icon: string;
  short: string;
  best_for: string;
  notable?: string;
  for_who: ("básico" | "medio" | "avanzado")[];
};

export const herramientas: Herramienta[] = [
  // ============ CHATBOTS ============
  {
    id: "chatgpt",
    name: "ChatGPT",
    by: "OpenAI",
    category: "chatbot",
    price: "freemium",
    url: "https://chatgpt.com",
    icon: "💬",
    short: "El chatbot que lo empezó todo. Sigue siendo la puerta de entrada para la mayoría.",
    best_for: "Uso general, multimodal (texto, voz, imagen, vídeo en Sora). Code Interpreter potente.",
    notable: "GPT-5 (gen actual). Plan Free, Plus ($20), Pro ($200).",
    for_who: ["básico", "medio", "avanzado"],
  },
  {
    id: "claude",
    name: "Claude",
    by: "Anthropic",
    category: "chatbot",
    price: "freemium",
    url: "https://claude.ai",
    icon: "🧠",
    short: "El favorito de escritores y developers. Ventana de contexto largísima.",
    best_for: "Escritura cuidada, código, análisis de documentos largos, razonamiento.",
    notable: "Claude Opus 4.7. Plan Free, Pro ($20), Max (~$100-200).",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "gemini",
    name: "Gemini",
    by: "Google",
    category: "chatbot",
    price: "freemium",
    url: "https://gemini.google.com",
    icon: "💎",
    short: "Integrado en Android, Gmail, Docs, Maps. Tiene 'búsqueda profunda'.",
    best_for: "Si vives en el ecosistema Google. Buenísimo multimodal.",
    notable: "Gemini 3 Pro. Modo 'Deep Research'.",
    for_who: ["básico", "medio", "avanzado"],
  },
  {
    id: "copilot",
    name: "Copilot",
    by: "Microsoft",
    category: "chatbot",
    price: "freemium",
    url: "https://copilot.microsoft.com",
    icon: "🪟",
    short: "El de Windows y Office. En empresas con M365 es la opción por defecto.",
    best_for: "Excel, Word, Outlook, Teams. Si tu empresa paga M365, ya lo tienes.",
    for_who: ["medio"],
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    by: "Meta",
    category: "chatbot",
    price: "gratis",
    url: "https://www.meta.ai",
    icon: "🟦",
    short: "Dentro de WhatsApp, Instagram, Messenger. Gratis sin instalar nada.",
    best_for: "Si ya usas WhatsApp y no quieres instalar otra app.",
    notable: "Escribe @Meta AI en cualquier chat.",
    for_who: ["básico"],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    by: "Perplexity AI",
    category: "investigacion",
    price: "freemium",
    url: "https://perplexity.ai",
    icon: "🔍",
    short: "Buscador conversacional con fuentes citadas. Sustituto de Google.",
    best_for: "Investigar temas serios con confianza. Cada respuesta lleva URLs.",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "grok",
    name: "Grok",
    by: "xAI",
    category: "chatbot",
    price: "pago",
    url: "https://grok.x.ai",
    icon: "𝕏",
    short: "El de Elon. Acceso a X en tiempo real. Menos filtros.",
    best_for: "Eventos en vivo, twitters al minuto. Personalidad menos formal.",
    for_who: ["medio"],
  },

  // ============ IMAGEN ============
  {
    id: "midjourney",
    name: "Midjourney",
    by: "Midjourney",
    category: "imagen",
    price: "pago",
    url: "https://midjourney.com",
    icon: "🎨",
    short: "Calidad artística top. El estándar de muchos diseñadores.",
    best_for: "Ilustración, conceptos visuales, estilo artístico definido.",
    notable: "Web propia, ya no solo Discord.",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "gpt-image",
    name: "GPT-Image",
    by: "OpenAI",
    category: "imagen",
    price: "freemium",
    url: "https://chatgpt.com",
    icon: "🖼️",
    short: "Dentro de ChatGPT. El mejor con texto en imágenes.",
    best_for: "Carteles, infografías, imágenes con palabras dentro.",
    for_who: ["básico", "medio"],
  },
  {
    id: "flux",
    name: "Flux",
    by: "Black Forest Labs",
    category: "imagen",
    price: "freemium",
    url: "https://blackforestlabs.ai",
    icon: "⚡",
    short: "Open-weight. El SOTA libre. Lo usan muchos servicios bajo capa.",
    best_for: "Calidad pro sin Midjourney. Se ejecuta en local con suficiente GPU.",
    for_who: ["avanzado"],
  },
  {
    id: "ideogram",
    name: "Ideogram",
    by: "Ideogram",
    category: "imagen",
    price: "freemium",
    url: "https://ideogram.ai",
    icon: "🔤",
    short: "Especialista en tipografía y logos.",
    best_for: "Logos, banners con texto largo, diseño tipográfico.",
    for_who: ["medio", "avanzado"],
  },

  // ============ VIDEO ============
  {
    id: "sora",
    name: "Sora",
    by: "OpenAI",
    category: "video",
    price: "freemium",
    url: "https://sora.com",
    icon: "🎬",
    short: "El que rompió internet en octubre 2025. App propia y dentro de ChatGPT.",
    best_for: "Clips cortos realistas, cameos con tu cara, audio sincronizado.",
    notable: "App #1 del App Store en 4 días tras lanzamiento.",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "veo",
    name: "Veo 3",
    by: "Google DeepMind",
    category: "video",
    price: "pago",
    url: "https://deepmind.google/models/veo/",
    icon: "📹",
    short: "Vídeo + música + voz integrada. Integrado en YouTube Shorts.",
    best_for: "Vídeos con audio que sale del propio modelo, sin combinar herramientas.",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "runway",
    name: "Runway",
    by: "Runway",
    category: "video",
    price: "freemium",
    url: "https://runwayml.com",
    icon: "🛫",
    short: "Veterano del vídeo IA. Herramientas pro: image-to-video, edición.",
    best_for: "Profesionales del vídeo. Tiene editor completo, no solo generación.",
    for_who: ["avanzado"],
  },
  {
    id: "kling",
    name: "Kling",
    by: "Kuaishou",
    category: "video",
    price: "freemium",
    url: "https://kling.kuaishou.com",
    icon: "🎥",
    short: "China. Calidad sorprendente, precio competitivo.",
    best_for: "Alternativa a Sora con coste menor. Físicas decentes.",
    for_who: ["medio", "avanzado"],
  },

  // ============ AUDIO ============
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    by: "ElevenLabs",
    category: "audio",
    price: "freemium",
    url: "https://elevenlabs.io",
    icon: "🎙️",
    short: "El referente para clonar voz y doblaje multilingüe.",
    best_for: "Audiolibros, narrar vídeos, doblar contenido manteniendo tu voz.",
    notable: "Bastan 30 segundos de audio limpio para clonar una voz.",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "suno",
    name: "Suno",
    by: "Suno",
    category: "audio",
    price: "freemium",
    url: "https://suno.com",
    icon: "🎵",
    short: "Canciones completas desde un prompt. Música indistinguible.",
    best_for: "Canciones de cumple, jingles, música personalizada.",
    for_who: ["básico", "medio"],
  },
  {
    id: "udio",
    name: "Udio",
    by: "Udio",
    category: "audio",
    price: "freemium",
    url: "https://udio.com",
    icon: "🎶",
    short: "Competidor de Suno. Pelean por la calidad sonora.",
    best_for: "Si no te convence Suno, prueba este. Estilos a veces complementarios.",
    for_who: ["medio"],
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    by: "Google",
    category: "audio",
    price: "gratis",
    url: "https://notebooklm.google.com",
    icon: "📔",
    short: "Convierte cualquier PDF en podcast tipo NPR con dos voces conversando.",
    best_for: "Estudiar, escuchar documentos en el coche, audio accesible para quien no lee.",
    notable: "Audio Overview de 12-20 min con dos voces que conversan, gratis.",
    for_who: ["básico", "medio", "avanzado"],
  },
  {
    id: "heygen",
    name: "HeyGen",
    by: "HeyGen",
    category: "video",
    price: "freemium",
    url: "https://heygen.com",
    icon: "🎭",
    short: "Avatares parlantes desde un guion. Tu cara hablando lo que escribiste.",
    best_for: "Vídeos corporativos, cursos, contenido en varios idiomas con tu avatar.",
    for_who: ["medio", "avanzado"],
  },

  // ============ TRABAJO ============
  {
    id: "manus",
    name: "Manus AI",
    by: "Manus",
    category: "agente",
    price: "freemium",
    url: "https://manus.ai",
    icon: "🤖",
    short: "Agente autónomo: le pides una tarea compleja, navega webs, escribe documentos.",
    best_for: "Tareas largas que requieren múltiples pasos y herramientas.",
    for_who: ["avanzado"],
  },
  {
    id: "gamma",
    name: "Gamma",
    by: "Gamma",
    category: "trabajo",
    price: "freemium",
    url: "https://gamma.app",
    icon: "🎯",
    short: "Presentaciones, documentos y webs desde un prompt.",
    best_for: "Pasar de idea a slides bonitas en minutos. Mejor que PowerPoint vacío.",
    for_who: ["medio"],
  },
  {
    id: "genspark",
    name: "Genspark",
    by: "Genspark",
    category: "trabajo",
    price: "freemium",
    url: "https://genspark.ai",
    icon: "✨",
    short: "Agentes para slides, hojas de cálculo, llamadas con voz.",
    best_for: "Construir presentaciones con datos reales, sin curro manual.",
    for_who: ["medio", "avanzado"],
  },

  // ============ DEVELOPER ============
  {
    id: "claude-code",
    name: "Claude Code",
    by: "Anthropic",
    category: "developer",
    price: "pago",
    url: "https://www.anthropic.com/claude-code",
    icon: "⌨️",
    short: "El CLI de Anthropic que ejecuta tareas reales en tu terminal.",
    best_for: "Desarrollo serio. Lee, escribe, corre comandos. Esta web la construyó él.",
    notable: "Plan mode, subagents, skills, MCP.",
    for_who: ["avanzado"],
  },
  {
    id: "cursor",
    name: "Cursor",
    by: "Cursor",
    category: "developer",
    price: "pago",
    url: "https://cursor.com",
    icon: "🖱️",
    short: "VSCode con IA profundamente integrada. Líder del segmento.",
    best_for: "Programar día a día con un copiloto que entiende todo el proyecto.",
    for_who: ["avanzado"],
  },
  {
    id: "v0",
    name: "v0",
    by: "Vercel",
    category: "developer",
    price: "freemium",
    url: "https://v0.app",
    icon: "🚀",
    short: "Genera webs y componentes React desde un prompt.",
    best_for: "Vibe coding. Prototipos web sin tocar código.",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "lovable",
    name: "Lovable",
    by: "Lovable",
    category: "developer",
    price: "freemium",
    url: "https://lovable.dev",
    icon: "❤️",
    short: "Apps web completas desde un prompt. De cero a app desplegada.",
    best_for: "Quien no sabe programar pero necesita una app interna o web pequeña.",
    notable: "Llegó a $100M ARR en 8 meses, récord histórico.",
    for_who: ["medio"],
  },
  {
    id: "bolt",
    name: "Bolt",
    by: "StackBlitz",
    category: "developer",
    price: "freemium",
    url: "https://bolt.new",
    icon: "⚡",
    short: "Como v0 y Lovable. Genera apps web completas en el navegador.",
    best_for: "Prototipos rápidos sin instalar nada.",
    for_who: ["medio", "avanzado"],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    by: "GitHub / Microsoft",
    category: "developer",
    price: "pago",
    url: "https://github.com/features/copilot",
    icon: "🐙",
    short: "El veterano del autocompletado IA. Ahora con modo agente.",
    best_for: "Si ya usas VSCode/JetBrains, integración instantánea.",
    for_who: ["avanzado"],
  },

  // ============ LOCAL / PRIVADO ============
  {
    id: "ollama",
    name: "Ollama",
    by: "Ollama",
    category: "local",
    price: "gratis",
    url: "https://ollama.com",
    icon: "🦙",
    short: "Ejecuta modelos en tu ordenador. Cero internet, cero coste recurrente.",
    best_for: "Privacidad total. Datos médicos, jurídicos, código confidencial.",
    notable: "ollama run llama3 y listo.",
    for_who: ["avanzado"],
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    by: "LM Studio",
    category: "local",
    price: "gratis",
    url: "https://lmstudio.ai",
    icon: "🏠",
    short: "Interfaz gráfica para descargar y chatear con modelos locales.",
    best_for: "Lo mismo que Ollama pero con UI bonita, sin terminal.",
    for_who: ["medio", "avanzado"],
  },

  // ============ INVESTIGACIÓN ============
  {
    id: "deep-research-gpt",
    name: "ChatGPT Deep Research",
    by: "OpenAI",
    category: "investigacion",
    price: "pago",
    url: "https://chatgpt.com",
    icon: "🔬",
    short: "Modo dentro de ChatGPT Pro. Investiga 30 minutos, te entrega informe con fuentes.",
    best_for: "Profundizar en un tema desde cero. Decisiones importantes.",
    for_who: ["avanzado"],
  },
  {
    id: "scite",
    name: "Scite",
    by: "Scite",
    category: "investigacion",
    price: "pago",
    url: "https://scite.ai",
    icon: "📊",
    short: "Buscador académico con IA. Te dice si un paper se contradice con otros.",
    best_for: "Investigación académica seria. Médicos, científicos, doctorandos.",
    for_who: ["avanzado"],
  },
];

export const herramientasByCategory = (cat: HerramientaCategory) =>
  herramientas.filter((h) => h.category === cat);

export const categoryLabels: Record<HerramientaCategory, { label: string; emoji: string }> = {
  chatbot: { label: "Chatbots generales", emoji: "💬" },
  imagen: { label: "Imagen", emoji: "🎨" },
  video: { label: "Vídeo", emoji: "🎬" },
  audio: { label: "Audio y música", emoji: "🎙️" },
  investigacion: { label: "Investigación", emoji: "🔍" },
  trabajo: { label: "Productividad", emoji: "💼" },
  developer: { label: "Developer", emoji: "💻" },
  agente: { label: "Agentes autónomos", emoji: "🤖" },
  local: { label: "Local / privado", emoji: "🔒" },
};

export const priceLabels: Record<HerramientaPrice, { label: string; color: string }> = {
  gratis: { label: "Gratis", color: "var(--color-good)" },
  freemium: { label: "Freemium", color: "var(--color-cool)" },
  pago: { label: "De pago", color: "var(--color-warn)" },
  api: { label: "Solo API", color: "var(--color-hot)" },
};
